require("core.keymaps.global")
require("core.keymaps.FT-quickfix")
require('core.keymaps.FT-shell')
require('core.keymaps.FT-markdown')
require('core.keymaps.FT-vimwiki')
require('core.keymaps.FT-copilot')
