-- require("ed-cmd").setup({
--   -- Those are the default options, you can just call setup({}) if you don't want to change the defaults
--   cmdline = {
--     keymaps = {
--       -- edit = ";j<Space>",
--       edit = "<Esc>",
--       execute = "<CR>",
--       close = "<C-C>",
--     },
--   },
--   -- You enter normal mode in the cmdline with edit, execute a
--   -- command from normal mode with execute and close the cmdline in
--   -- normal mode with close
--   pumenu = { max_items = 100 },
-- })
