require("core.plugin_config.tokyonight")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
-- DEPRECATED:: 2024-12-28
-- require("core.plugin_config.coc")
require("core.plugin_config.calendar")
require("core.plugin_config.vimwiki")
require("core.plugin_config.gh")
require("core.plugin_config.colorizer")
require("core.plugin_config.lualine")
--require("core.plugin_config.spectre")
require("core.plugin_config.devicons")
-- DEPRECATED:: 2024-12-28
-- require("core.plugin_config.flutter-tools")
require("core.plugin_config.winshift")
--require("core.plugin_config.shade")
require("core.plugin_config.toggleterm")
require("core.plugin_config.image")
-- DEPRECATED:: 2024-12-28
-- require("core.plugin_config.outline")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.markdown-preview")
require("core.plugin_config.todo-comments")
require("core.plugin_config.gitsigns")
require("core.plugin_config.diffview")
require("core.plugin_config.alpha")
require("core.plugin_config.render-markdown")
require("core.plugin_config.quicker")
require("core.plugin_config.faster")
require("core.plugin_config.toggleterm-manager")
require("core.plugin_config.oil")
require("core.plugin_config.avante")
require("core.plugin_config.harpoon")
require("core.plugin_config.aerial")
require("core.plugin_config.focus")
require("core.plugin_config.dressing")
require("core.plugin_config.nvim-ufo")
require("core.plugin_config.nvim-cmp")
