-- -- 사용자 정의 tabline 함수
-- function MyTabLine()
--   local s = ''
--   local sep = ' | ' -- 탭 구분자
--
--   for i = 1, vim.fn.tabpagenr('$') do
--     -- 현재 탭 페이지를 강조 표시
--     if i == vim.fn.tabpagenr() then
--       s = s .. '%' .. i .. 'T' .. ' ' .. vim.fn.gettabvar(i, 'tabname', 'Tab ' .. i) .. ' '
--     else
--       s = s .. '%' .. i .. 'T' .. ' ' .. vim.fn.gettabvar(i, 'tabname', 'Tab ' .. i) .. ' '
--     end
--
--     if i < vim.fn.tabpagenr('$') then
--       s = s .. sep
--     end
--   end
--
--   s = s .. '%='
--
--   return s
-- end
--
-- -- tabline 설정
-- vim.o.tabline = '%!v:lua.MyTabLine()'
--
-- -- 새로운 탭을 열 때 탭 이름을 입력받기 위한 함수
-- function NewTabWithPrompt()
--   -- 입력 프롬프트 표시
--   local tabname = vim.fn.input('Enter tab name: ')
--   if tabname == '' then
--     tabname = 'Tab ' .. vim.fn.tabpagenr('$') + 1
--   end
--   -- 새로운 탭 생성 및 이름 설정
--   vim.cmd('tabnew')
--   local tabnr = vim.fn.tabpagenr()
--   vim.fn.settabvar(tabnr, 'tabname', tabname)
-- end
--
-- -- 사용자 정의 명령어로 NewTabWithPrompt 함수 매핑
-- vim.api.nvim_create_user_command('TabNew', NewTabWithPrompt, {})
--
-- -- -- 기존의 :tabnew 명령어를 재정의
-- -- vim.cmd('command! -nargs=* TabNew lua NewTabWithPrompt()')
